завдання 1, програмування
ZvarunVolodymyr/programming pull request #1
Opened 2021-09-10 06:54 UTC by ZvarunVolodymyr

9 варіант

2021-09-16 11:58 UTC, tetianastoyko requested changes

2021-09-16 11:58 UTC, tetianastoyko commented on main.py
> +    for i in range(n - 1):
Звідси мав би початись метод, який робить основну задачу, а введення - це поза межами цього методу

2021-09-16 14:17 UTC, ZvarunVolodymyr reviewed
розділення зчитування та алгоритму

2021-09-17 06:07 UTC, ZvarunVolodymyr reviewed
додано keyboard interrupt

2021-10-05 07:19 UTC, merged